# Generated by Django 3.0.6 on 2020-06-27 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=50, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('room_no', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pic')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
